### ISSUE TITLE
Web Socket support is Broken

### ISSUE THREAD

**Issue by slmnhq** [play-co/hookbox#49]
How To Reproduce:

Follow the steps to run the "python_graphic_eq" demo.
Open http://localhost:8080 in Google Chrome (v6.0.472.0 or later).
Observe that the hookbox process prints the following message:
  "access - INFO - Incoming WebSocket connection 127.0.0.1       127.0.0.1:2974"
Observe that the slider bars do not update dynamically.
Open the "Resources" tab in the browser's developer tools.
Observe that it does not report any XHR traffic.

This problem was reproduced on Ubuntu Lucid Lynx.

**Comment by mcarter** [comment]
This is a bug in eventlet, actually. The problem is that eventlet 0.9.9 is installed when you install hookbox, but you need eventlet 0.9.10dev. Try: "easy_install eventlet==dev" and that should fix the problem.

I forgot about this; we need to force hookbox to pick up the dev version somehow. I had some trouble setting that requirement in hookbox's setup.py, unfortunately.

**Comment by slmnhq** [comment]
Confirmed.
